#
# Module manifest for module 'FFUUI.Core'
#
# Generated by: Richard Balsley
#
# Generated on: 6/11/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'FFUUI.Core.psm1'

# Version number of this module.
ModuleVersion = '0.0.13'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '826c5868-c452-48a9-a3d8-9ff7fea54feb'

# Author of this module
Author = 'Richard Balsley'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) Richard Balsley. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Core UI logic for the FFU Builder application.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('..\FFU.Common\FFU.Common.psd1')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('FFUUI.Core.Applications.psm1',
                'FFUUI.Core.Config.psm1',
                'FFUUI.Core.Drivers.psm1',
                'FFUUI.Core.Drivers.Dell.psm1',
                'FFUUI.Core.Drivers.HP.psm1',
                'FFUUI.Core.Drivers.Lenovo.psm1',
                'FFUUI.Core.Drivers.Microsoft.psm1',
                'FFUUI.Core.Handlers.psm1',
                'FFUUI.Core.Initialize.psm1',
                'FFUUI.Core.Shared.psm1',
                'FFUUI.Core.WindowsSettings.psm1',
                'FFUUI.Core.Winget.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
v0.0.12: VMware NetworkType and NicType UI settings
- ADDED: VMware Network Type dropdown (NAT/Bridged/Host-Only)
- ADDED: VMware NIC Type dropdown (E1000E/VMXNET3/E1000)
- Both dropdowns visible only when VMware Workstation Pro selected
- Config save/load support for VMwareNetworkType and VMwareNicType
- Defaults: NAT for network type, E1000E for NIC type
- E1000E recommended for WinPE compatibility, VMXNET3 for best performance

v0.0.11: VM Shutdown Timeout UI + REST API cleanup
- ADDED: VMShutdownTimeoutMinutes control in VM Settings tab (5-120 minutes)
- CHANGED: Default timeout increased from 20 to 60 minutes for larger builds
- REMOVED: VMware REST API credential UI (vmrest.exe no longer used)
- REMOVED: vmrest configuration button and credential status indicator
- FIXED: VM Settings tab spacing issues (proper grid rows instead of margin offsets)
- The FFU.Hypervisor module now uses vmrun.exe directly without authentication

v0.0.10: VMware bridged network IP auto-detection
- NEW: Get-VMwareHostIPAddress function for automatic host IP detection
- FIXED: VMHostIPAddress now preserved when switching from Hyper-V to VMware
- If Hyper-V vSwitch IP is already populated, it's valid for VMware too (same physical adapter)
- Auto-detection fallback for VMware-only systems (detects primary adapter via default route)
- Enhanced CaptureFFU.ps1 diagnostics with network segment comparison
- BuildFFUVM.ps1 now logs network adapters and validates VMHostIPAddress for VMware
- Resolves Error 53 (network path not found) when using VMware bridged networking

v0.0.9: Force VMware Driver Download checkbox
- Added "Re-download VMware network drivers" checkbox in VM Settings tab
- Visible only when VMware Workstation Pro is selected as hypervisor
- Forces fresh download of Intel e1000e drivers even if folder exists
- Useful when previous download failed or drivers appear corrupted
- Config save/load support for ForceVMwareDriverDownload setting

v0.0.8: VMware REST API credential input fields
- Added Username and Password fields to VM Settings tab for VMware
- Credentials are saved to config and loaded on startup
- Status indicator shows: "Ready", "Using vmrest.cfg", or "Enter credentials"
- Credentials passed to VMwareProvider for REST API authentication
- Eliminates need for vmrun.exe fallback when credentials are entered

v0.0.7: ShowVMConsole option for VMware
- Added "Show VM Console" checkbox in VM Settings (VMware only)
- Allows viewing Windows installation progress during build
- Config save/load support for ShowVMConsole setting
- Auto-hides when Hyper-V selected (use Hyper-V Manager for console)

v0.0.6: Fix vmrest.cfg filename detection
- VMware 17.x uses 'vmrest.cfg' (no leading dot), not '.vmrestCfg'
- UI now checks both filename variants for credential detection
- Fixes "Not configured" status showing even after credentials are set up

v0.0.5: Enterprise account support for VMware credentials
- Removed elevation from credential setup button (was causing issues with separate admin accounts)
- Status now shows "Configured (current user)" to clarify per-profile storage
- Added enterprise guidance in terminal output and dialog messages
- Updated tooltips to explain separate admin account requirements
- Added dynamic tooltip on status text showing current username

v0.0.4: VMware REST API credential setup UI
- Added VMware REST API row in VM Settings tab (visible when VMware selected)
- Added credential status indicator (Configured/Not configured)
- Added "Configure Credentials..." button that opens terminal for vmrest.exe -C
- Button launches elevated cmd.exe with guided vmrest credential setup
- Status refreshes automatically after configuration complete

v0.0.3: Hypervisor selection dropdown
- Added Hypervisor Type dropdown (Hyper-V, VMware Workstation Pro, Auto-detect)
- Added Hypervisor Status indicator with availability check
- Show/hide Hyper-V specific controls based on selection

v0.0.2: Bug fix
- Fixed expand.exe argument quoting in FFUUI.Core.Drivers.HP.psm1
- Removed embedded quotes from argument arrays (3 instances)
- Prevents "Can't open input file" errors when HP driver paths contain spaces

v0.0.1: Initial release
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

