# Analyze options for configuring VMware bridge adapter selection

Write-Host "=== VMware Bridge Configuration Analysis ===" -ForegroundColor Cyan

# Option 1: Check which adapters are currently bound to VMnetBridge
Write-Host "`n--- Option 1: VMnetBridge Linkage Bindings ---" -ForegroundColor Yellow
Write-Host "These are adapters the VMware Bridge Protocol can use:" -ForegroundColor Gray

$linkage = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\VMnetBridge\Linkage' -EA SilentlyContinue

# Correlate with network adapters
$adapters = Get-NetAdapter
$bindGuids = $linkage.Bind | ForEach-Object { ($_ -replace '\\Device\\', '' -replace '[{}]', '').ToUpper() }

Write-Host "`nAdapters currently bound to VMnetBridge:" -ForegroundColor White
foreach ($adapter in $adapters) {
    $guidUpper = $adapter.InterfaceGuid.ToString().ToUpper() -replace '[{}]', ''
    $isBound = $bindGuids -contains $guidUpper

    if ($isBound) {
        $status = if ($adapter.Status -eq 'Up') { '[UP]' } else { '[DOWN]' }
        Write-Host "  [BOUND] $($adapter.InterfaceDescription) $status" -ForegroundColor Green
    }
}

Write-Host "`nAdapters NOT bound to VMnetBridge:" -ForegroundColor White
foreach ($adapter in $adapters) {
    $guidUpper = $adapter.InterfaceGuid.ToString().ToUpper() -replace '[{}]', ''
    $isBound = $bindGuids -contains $guidUpper

    if (-not $isBound) {
        Write-Host "  [NOT BOUND] $($adapter.InterfaceDescription)" -ForegroundColor DarkYellow
    }
}

# Option 2: Check if netmap.conf can be manually created
Write-Host "`n--- Option 2: Create netmap.conf ---" -ForegroundColor Yellow
Write-Host "On Linux, netmap.conf includes 'add_bridge_mapping' entries." -ForegroundColor Gray
Write-Host "On Windows, the format appears to be different." -ForegroundColor Gray

# Check if we can figure out the Windows netmap.conf format
$netmapPath = "C:\ProgramData\VMware\netmap.conf"
if (Test-Path $netmapPath) {
    Write-Host "`nnetmap.conf exists:" -ForegroundColor Green
    Get-Content $netmapPath
} else {
    Write-Host "`nnetmap.conf does not exist - would be created by Virtual Network Editor" -ForegroundColor DarkYellow

    # Try to create a sample netmap.conf based on Linux format
    Write-Host "`nSample netmap.conf that could work (based on Linux format):" -ForegroundColor Cyan
    $sampleNetmap = @"
# This file is automatically generated.
# Hand-editing this file is not recommended.
network0.name = "Bridged"
network0.device = "vmnet0"
network1.name = "HostOnly"
network1.device = "vmnet1"
network8.name = "NAT"
network8.device = "vmnet8"
"@
    Write-Host $sampleNetmap
}

# Option 3: Check preferences.ini for user settings
Write-Host "`n--- Option 3: User Preferences ---" -ForegroundColor Yellow
$prefsPath = "$env:APPDATA\VMware\preferences.ini"
if (Test-Path $prefsPath) {
    Write-Host "Found preferences.ini:" -ForegroundColor Green
    Get-Content $prefsPath | Select-String -Pattern 'vmnet|bridge|network' -AllMatches
} else {
    Write-Host "No preferences.ini found at $prefsPath" -ForegroundColor DarkYellow
}

# Option 4: Try to find where auto-bridging exclusions are stored
Write-Host "`n--- Option 4: Auto-Bridging Exclusions ---" -ForegroundColor Yellow
Write-Host "In Virtual Network Editor, you can exclude adapters from auto-bridging." -ForegroundColor Gray
Write-Host "Looking for where this setting is stored..." -ForegroundColor Gray

# Search for any registry entries with 'exclude' or 'autobridge'
$searchPaths = @(
    'HKLM:\SOFTWARE\WOW6432Node\VMware, Inc.',
    'HKCU:\Software\VMware, Inc.'
)

foreach ($searchPath in $searchPaths) {
    if (Test-Path $searchPath) {
        Get-ChildItem -Path $searchPath -Recurse -EA SilentlyContinue | ForEach-Object {
            $props = Get-ItemProperty -Path $_.PSPath -EA SilentlyContinue
            foreach ($prop in $props.PSObject.Properties) {
                if ($prop.Name -match 'exclude|autobridge|bridge') {
                    Write-Host "Found: $($_.PSPath) - $($prop.Name): $($prop.Value)" -ForegroundColor Green
                }
            }
        }
    }
}

# Summary and recommendations
Write-Host "`n=== SUMMARY ===" -ForegroundColor Cyan
Write-Host @"

Based on the analysis, here are the options for configuring VMware bridging:

1. MANUAL CONFIGURATION (Recommended for now):
   - Open Virtual Network Editor (vmnetcfg.exe)
   - Select VMnet0
   - Change 'Bridged to:' from 'Automatic' to specific adapter
   - Click 'Automatic Settings' to exclude VPN adapters

2. REGISTRY MANIPULATION (Advanced, may break VMware):
   - Could try modifying VMnetBridge\Linkage\Bind to remove unwanted adapters
   - Requires service restart and may not persist

3. VMX-LEVEL WORKAROUND:
   - Use 'connectionType = custom' with a specific vmnet
   - Configure that vmnet to bridge to the correct adapter

4. NETMAP.CONF CREATION (Untested on Windows):
   - Manually create C:\ProgramData\VMware\netmap.conf
   - May need specific Windows format

"@ -ForegroundColor White
