#
# Module manifest for module 'FFU.Common'
#
# Generated by: Richard Balsley
#
# Generated on: 6/11/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'FFU.Common.Core.psm1'

# Version number of this module.
ModuleVersion = '0.0.6'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '7dac2b8f-e65a-4997-961e-7a5ef5161901'

# Author of this module
Author = 'Richard Balsley'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) Richard Balsley. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Common functions shared between FFU Builder UI and the BuildFFUVM.ps1 build script.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('FFU.Common.Classes.psm1',
               'FFU.Common.Drivers.psm1',
               'FFU.Common.Winget.psm1',
               'FFU.Common.Parallel.psm1',
               'FFU.Common.Cleanup.psm1',
               'FFU.Common.Download.psm1',
               'FFU.Common.ParallelDownload.psm1',
               'FFU.Common.Logging.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
v0.0.6: Defense-in-depth fix for log monitoring after module -Force import
- Fixed: Monitor tab STILL showing only "Build started" after v0.0.5 fix
- Root cause: BuildFFUVM.ps1 imports FFU.Common with -Force, which resets the script-scoped
  $CommonCoreMessagingContext variable to $null, breaking real-time UI updates
- Solution: BuildFFUVM.ps1 now restores messaging context immediately after -Force import
- 3 new regression tests to prevent this issue from recurring
- Comprehensive documentation of the defense-in-depth pattern

v0.0.5: Log monitoring UI fix - Real-time WriteLog integration with messaging queue
- Added Set-CommonCoreMessagingContext function for setting FFU.Messaging queue context
- Modified WriteLog to write to both log file AND messaging queue when context is set
- Fixes Monitor tab only showing "Build started" - now shows all log entries in real-time
- Queue writes work even when log file path isn't set (for UI-only scenarios)
- Defense-in-depth: Warns only when neither file nor queue destinations are available
- 20 new Pester tests for log monitoring functionality

v0.0.4: Invoke-Process error handling improvements
- Enhanced Invoke-Process to provide structured error messages with process path, exit code, and stderr/stdout
- Error messages now follow format: "Process '{path}' exited with code {code}. Error/Output: {message}"
- Helps diagnose failures like oscdimg.exe errors by showing actual exit codes instead of just stdout
- Prevents confusing error messages where progress output was shown as the error

v0.0.3: Log file initialization fix
- Enhanced Set-CommonCoreLogPath with -Initialize switch parameter for proper log file lifecycle management
- When -Initialize is specified, deletes existing log file before initializing new session
- Fixes bug where log file was deleted AFTER path was set, causing WriteLog to fail
- Centralized log file deletion logic (removed redundant deletion from BuildFFUVM.ps1 and UI)

v0.0.2: Phase 2 Reliability improvements
- Added FFU.Common.Logging module for structured logging with log levels, JSON output, and session correlation
- Enhanced WriteLog to accept null/empty strings gracefully (fixes parameter binding errors)
- Added Get-ErrorMessage helper function for safe error message extraction
- Added path validation before Remove-Item in Invoke-Process

v0.0.1: Initial release
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

